version: "3.7"
services:
  dev-db:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: nest
    volumes:
      - ./prisma/migrations:/migrations
    networks:
      - networkName
networks:
  networkName: